version: '3'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutorial-api
    ports:
      - '8000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0-oracle
    restart: always
    container_name: tutorial-mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD
volumes:
  node_modules:
  db_data:
